name: Deploy-staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_API_URL: "https://api.staging.horaro.net/api/v1/"
          envkey_REACT_APP_NAME: "Horaro"
          file_name: .env

      - name: Copy env file
        uses: appleboy/scp-action@master
        with:
          host: staging.horaro.net
          username: ubuntu
          key: ${{ secrets.AWS_HORARO_PRYVATE_KEY }}
          source: ".env"
          target: "~/staging_horaro/HoraroFrontend/"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action

      - name: Build Backend
        id: docker_build_backend
        uses: docker/build-push-action
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ivan556/horaro-frontend

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: staging.horaro.net
          username: ubuntu
          key: ${{ secrets.AWS_HORARO_PRYVATE_KEY }}
          script: | 
                  cd ~/staging_horaro/HoraroFrontend/ &&\
                  git pull && cd .. &&\ 
                  make staging_up_and_build_one_service service=front

