name: Deploy-staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: 46.229.214.105
          username: prod
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: | 
                  cd ~/staging_horaro/HoraroFrontend/ &&\
                  git pull && cd .. &&\ 
                  make up_and_build_one_service service=front
