name: Deploy-staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: 46.229.214.105
          username: prod
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: cd ~/staging_horaro/HoraroFrontend/ && git pull && cd .. && docker stop staging_horaro_front_1 && docker-compose up -d --no-deps --build front && docker image prune -f