name: Deploy-staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: staging.horaro.net
          username: ubuntu
          key: ${{ secrets.AWS_HORARO_PRYVATE_KEY }}
          script: | 
                  cd ~/staging_horaro/HoraroFrontend/ &&\
                  git pull && cd .. &&\ 
                  make up_and_build_one_service service=front
