name: Deploy-staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_API_URL: "https://api.staging.horaro.net/api/v1/"
          envkey_REACT_APP_NAME: "Horaro"
          file_name: .env

      - name: Copy env file
        uses: appleboy/scp-action@master
        with:
          host: staging.horaro.net
          username: ubuntu
          key: ${{ secrets.AWS_HORARO_PRYVATE_KEY }}
          source: ".env"
          target: "~/staging_horaro/HoraroFrontend/"

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build FrontEnd
        id: docker_build_frontend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ivan556/horaro-frontend

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: staging.horaro.net
          username: ubuntu
          key: ${{ secrets.AWS_HORARO_PRYVATE_KEY }}
          script: |
                  cd ~/staging_horaro/;
                  [[ -d HoraroBot/ ]] || git clone git@github.com:Horaroo/HoraroBot.git;
                  [[ -d HoraroBackend/ ]] || git clone git@github.com:Horaroo/HoraroBackend.git; 
                  [[ -d HoraroFrontend/ ]] || git clone git@github.com:Horaroo/HoraroFrontend.git; 
 
                  cd ~/staging_horaro &&\
                  docker-compose -f docker-compose.staging.yml pull &&\
                  make staging_up_and_build_one_service service=front

                  curl -XPOST \
                  -H 'Content-Type: application/json' \
                  -d '{ "text": "*successfull front deployed to staging*" }' \
                  'https://telepush.dev/api/messages/${{ secrets.TELEPUSH_TOKEN }}'